---
name: Build and Test

on:
  push:
    branches-ignore:
      - main

  workflow_call:

jobs:
  test:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint the dockerfile
        uses: rusty-actions/dockerfile-linter@v1
        with:
          dockerfile: './Dockerfile'

      - name: Determine version and create changelog
        id: bumper
        uses: tomerfi/version-bumper-action@1.1.3
        with:
          changelog: false

      - name: Update Cargo Version
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "./Cargo.toml"
          key: "package.version"
          value: "${{ steps.bumper.outputs.new_version }}"

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker build . -t slack-message:dev

      - name: Test the action
        env:
          INPUT_MESSAGE: "Build testing slack message"
          INPUT_WEBHOOK: ${{ secrets.SLACK_BUILD_WEBHOOK }}
        id: test
        run: |
          docker run --env INPUT_MESSAGE --env INPUT_WEBHOOK \
            --env GITHUB_REPOSITORY --env GITHUB_EVENT_NAME \
            --env GITHUB_REF --env GITHUB_SHA \
             slack-message:dev
